name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        # Release Please v4 automatically looks for .release-please-config.json 
        # and .release-please-manifest.json in the repository root.
